version: "3"
services:

  keycloak:
    image: restfulci/auth-server-docker:8da072f0160c76d9698c4bd7374644022925d8ab
    ports:
      # TODO:
      # Use 8443 instand for SSL.
      - "8880:8080"
    environment:
      KEYCLOAK_USER: restfulci
      KEYCLOAK_PASSWORD: secretpassword
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - keycloak-postgres

  keycloak-postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  job-postgres:
    image: restfulci/job-postgres:8da072f0160c76d9698c4bd7374644022925d8ab
    environment:
      - POSTGRES_DB=restfulci-job
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  job-rabbitmq:
    image: rabbitmq:3.8.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=restfulci
      - RABBITMQ_DEFAULT_PASS=secretpassword
    ports:
      - "15673:15672"

  job-minio:
    image: minio/minio:RELEASE.2020-12-26T01-35-54Z
    environment:
      - MINIO_ACCESS_KEY=restfulci
      - MINIO_SECRET_KEY=secretpassword
    command: server /data

  job-master-api-server:
    image: restfulci/job-master-api-server:8da072f0160c76d9698c4bd7374644022925d8ab
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH_SERVER_URI=http://localhost:8880
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - RABBITMQ_DEFAULT_USER=restfulci
      - RABBITMQ_DEFAULT_PASS=secretpassword
      - MINIO_ACCESS_KEY=restfulci
      - MINIO_SECRET_KEY=secretpassword
    ports:
      - "8881:8080"
    depends_on:
      - job-postgres
      - job-rabbitmq
      - job-minio
      - keycloak
    tty: true
    restart: always

  job-slave-executor:
    image: restfulci/job-slave-executor:8da072f0160c76d9698c4bd7374644022925d8ab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $SSH_AUTH_SOCK:${SSH_AUTH_SOCK}
    environment:
      - SSH_AUTH_SOCK
      - SPRING_PROFILES_ACTIVE=docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - RABBITMQ_DEFAULT_USER=restfulci
      - RABBITMQ_DEFAULT_PASS=secretpassword
      - MINIO_ACCESS_KEY=restfulci
      - MINIO_SECRET_KEY=secretpassword
    depends_on:
      - job-postgres
      - job-rabbitmq
      - job-minio
    tty: true
    restart: always

  pipeline-postgres:
    image: restfulci/pipeline-postgres:8da072f0160c76d9698c4bd7374644022925d8ab
    environment:
      - POSTGRES_DB=restfulci-pipeline
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  pipeline-api-cron-server:
    image: restfulci/pipeline-api-cron-server:8da072f0160c76d9698c4bd7374644022925d8ab
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8882:8080"
    depends_on:
      - pipeline-postgres
      - job-master-api-server
    tty: true
    restart: always
