version: "3"
services:

  job-postgres:
    image: postgres:14.2
    ports:
      - "5433:5432"
    volumes:
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - POSTGRES_DB=restfulci-job
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  job-rabbitmq:
    image: rabbitmq:3.9.13-management
    environment:
      - RABBITMQ_DEFAULT_USER=restfulci
      - RABBITMQ_DEFAULT_PASS=secretpassword
    ports:
      - "5673:5672"
      - "15673:15672"

  job-minio:
    image: minio/minio:RELEASE.2022-03-05T06-32-39Z
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=restfulci
      - MINIO_SECRET_KEY=secretpassword
    command: server /data

  keycloak:
    image: restfulci/auth-server-local:60644c34f3c6cb1ffa31b3ff45aeb36138afeb09
    ports:
      # TODO:
      # Use 8443 instand for SSL.
      - "8880:8080"
    environment:
      KEYCLOAK_USER: restfulci
      KEYCLOAK_PASSWORD: secretpassword
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - keycloak-postgres

  # keycloak:
  #   image: quay.io/keycloak/keycloak:17.0.0
  #   ports:
  #     # TODO:
  #     # Use 8443 instand for SSL.
  #     - "8880:8080"
  #   environment:
  #     KEYCLOAK_USER: restfulci
  #     KEYCLOAK_PASSWORD: secretpassword
  #     # https://keycloak.discourse.group/t/cant-import-realm-using-docker-image/259/8
  #     # otherwise see error "Script upload is disabled"
  #     KEYCLOAK_IMPORT: "/tmp/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"
  #     DB_VENDOR: POSTGRES
  #     DB_ADDR: keycloak-postgres
  #     DB_DATABASE: keycloak
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #   volumes:
  #     - ../auth-microservice/realm.json:/tmp/realm.json
  #   depends_on:
  #     - keycloak-postgres

  keycloak-postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
