version: "3"
services:

  job-postgres:
    image: postgres:13.1
    ports:
      - "5433:5432"
    volumes:
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      # TODO: Change name from `restfulci` to `restfulci-job`
      - POSTGRES_DB=restfulci
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  job-rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - "5673:5672"
      - "15673:15672"

  job-minio:
    image: minio/minio:RELEASE.2020-12-26T01-35-54Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: restfulci
      MINIO_SECRET_KEY: secretpassword
    command: server /data

  keycloak:
    image: restfulci/auth-server-local:85d65d5882575a554aa605158d16beacae4ba499
    ports:
      # TODO:
      # Use 8443 instand for SSL.
      - "8880:8080"
    environment:
      KEYCLOAK_USER: restfulci
      KEYCLOAK_PASSWORD: secretpassword
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - keycloak-postgres

  # keycloak:
  #   image: quay.io/keycloak/keycloak:11.0.2
  #   ports:
  #     # TODO:
  #     # Use 8443 instand for SSL.
  #     - "8880:8080"
  #   environment:
  #     KEYCLOAK_USER: restfulci
  #     KEYCLOAK_PASSWORD: secretpassword
  #     # https://keycloak.discourse.group/t/cant-import-realm-using-docker-image/259/8
  #     # otherwise see error "Script upload is disabled"
  #     KEYCLOAK_IMPORT: "/tmp/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"
  #     DB_VENDOR: POSTGRES
  #     DB_ADDR: keycloak-postgres
  #     DB_DATABASE: keycloak
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #   volumes:
  #     - ../auth-microservice/realm.json:/tmp/realm.json
  #   depends_on:
  #     - keycloak-postgres

  keycloak-postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
