version: "3"
services:

  postgres:
    image: postgres:12.1
    ports:
      - "5433:5432"
    volumes:
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      # TODO: Change name from `restfulci` to `restfulci-job`
      - POSTGRES_DB=restfulci
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  rabbitmq:
    image: rabbitmq:3.8.2-management
    ports:
      - "5673:5672"
      - "15673:15672"

  minio:
    image: minio/minio:RELEASE.2020-04-02T21-34-49Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: restfulci
      MINIO_SECRET_KEY: secretpassword
    command: server /data

  keycloak:
    image: quay.io/keycloak/keycloak:11.0.2
    ports:
      - "8880:8080"
    environment:
      KEYCLOAK_USER: restfulci
      KEYCLOAK_PASSWORD: secretpassword
      # TODO:
      # Change to postgres and setup the keycloak database.
      DB_VENDOR: h2
