version: "3"
services:

  postgres:
    image: postgres:12.1
    ports:
      - "5433:5432"
    volumes:
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      # TODO: Change name from `restfulci` to `restfulci-job`
      - POSTGRES_DB=restfulci
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  rabbitmq:
    image: rabbitmq:3.8.2-management
    ports:
      - "5673:5672"
      - "15673:15672"

  minio:
    image: minio/minio:RELEASE.2020-04-02T21-34-49Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: restfulci
      MINIO_SECRET_KEY: secretpassword
    command: server /data

  # Keycloak scripts are in path of `/opt/jboss/keycloak/bin` of the container.
  # Detail usage can be seem from https://hub.docker.com/r/jboss/keycloak
  #
  # `realm.json` can be saved from keycloak UI. Command line seems doesn't work:
  # docker-compose -f docker-compose.dev.yml exec keycloak /opt/jboss/keycloak/bin/standalone.sh -Djboss.socket.binding.port-offset=100 -Dkeycloak.migration.action=export -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.realmName=restfulci -Dkeycloak.migration.usersExportStrategy=REALM_FILE -Dkeycloak.migration.file=keycloak/realm.json
  #
  # TODO:
  # Move keycloak logic to a standalone auth microservice.
  # Bake realm.json into the image.
  # But it is kind of hard, because client (master-api-server) URL
  # need to be included in Keycloak setup.
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.2
    ports:
      - "8880:8080"
    environment:
      KEYCLOAK_USER: restfulci
      KEYCLOAK_PASSWORD: secretpassword
      # https://keycloak.discourse.group/t/cant-import-realm-using-docker-image/259/8
      # otherwise see error "Script upload is disabled"
      KEYCLOAK_IMPORT: "/tmp/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"
      # TODO:
      # Change to postgres and setup the keycloak database.
      DB_VENDOR: h2
    volumes:
      - ./keycloak/realm.json:/tmp/realm.json
