version: "3"
services:

  database:
    image: postgres:12.1
    ports:
      - "5433:5432"
    volumes:
      - ./database:/database
      - ./database/docker_init.sh:/docker-entrypoint-initdb.d/docker_init.sh
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  rabbitmq:
    image: rabbitmq:3.8.2-management
    ports:
      - "5673:5672"
      - "15673:15672"

  minio:
    image: minio/minio:RELEASE.2020-04-02T21-34-49Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: restfulci
      MINIO_SECRET_KEY: secretpassword
    command: server /data
