version: "3"
services:

  database:
    image: postgres:12.1
    volumes:
      - ./database:/database
      - ./database/docker_init.sh:/docker-entrypoint-initdb.d/docker_init.sh
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  rabbitmq:
    image: rabbitmq:3.8.2-management
    ports:
      - "15673:15672"

  master-api:
    build:
      context: ./master-api
      dockerfile: ./Dockerfile
    ports:
      - "8881:8080"
    depends_on:
      - database
      - rabbitmq
    tty: true
    restart: always

  slave-agent:
    build:
      context: ./slave-agent
      dockerfile: ./Dockerfile
    depends_on:
      - database
      - rabbitmq
    tty: true
    restart: always
