apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: restfulci
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
  - image: restfulci/job-master-api-server
    context: master-api
  - image: restfulci/job-slave-executor
    context: slave-agent
deploy:
  kubectl:
    manifests:
    - job/kubernetes/master-api-server-deployment.yaml
    - job/kubernetes/master-api-server-service.yaml
    - job/kubernetes/minio-standalone-deployment.yaml
    - job/kubernetes/minio-standalone-pvc.yaml
    - job/kubernetes/minio-standalone-service.yaml
    - job/kubernetes/postgres-deployment.yaml
    - job/kubernetes/postgres-service.yaml
    - job/kubernetes/rabbitmq-deployment.yaml
    - job/kubernetes/rabbitmq-service.yaml
    - job/kubernetes/slave-executor-deployment.yaml
