apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: restfulci
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
  - image: restfulci/job-master-api-server
    context: job-microservice/master-api
  - image: restfulci/job-slave-executor
    context: job-microservice/slave-agent
deploy:
  kubectl:
    manifests:
    - job-microservice/kubernetes/*.yaml
