apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: restfulci
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
  - image: restfulci/auth-server-kubernetes
    context: auth-microservice
    docker:
      buildArgs:
        AUTH_ENV: kubernetes
  - image: restfulci/job-master-api-server
    context: job-microservice/master-api
  - image: restfulci/job-slave-executor
    context: job-microservice/slave-agent
  - image: restfulci/job-postgres
    context: job-microservice/database
  - image: restfulci/pipeline-api-cron-server
    context: pipeline-microservice/api-cron
  - image: restfulci/pipeline-postgres
    context: pipeline-microservice/database
  - image: restfulci/job-frontend
    context: job-frontend
deploy:
  kubectl:
    manifests:
    - auth-microservice/kubernetes/*.yaml
    - job-microservice/kubernetes/*.yaml
    - pipeline-microservice/kubernetes/*.yaml
    - job-frontend/kubernetes/*.yaml
