apiVersion: v1

kind: Service
metadata:
  name: restfulci-job-master-api-server
  namespace: job-api
  labels:
    app: master-api-server
spec:
  type: LoadBalancer
  selector:
    app: master-api-server
  ports:
  - port: 80
    targetPort: 8080
