apiVersion: apps/v1

kind: Deployment
metadata:
  name: restfulci-job-master-api-server
  namespace: job-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: master-api-server
  template:
    metadata:
      labels:
        app: master-api-server
    spec:
      containers:
      - name: master-api-server
        image: restfulci/job-master-api-server:4bc2625a429243f0c730b7463100e2a0909fc0d2
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        resources:
          requests:
            cpu: 300m
