apiVersion: apps/v1

kind: Deployment
metadata:
  name: restfulci-job-master-api-server
  namespace: job
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: master-api-server
  template:
    metadata:
      labels:
        app: master-api-server
    spec:
      containers:
      - name: master-api-server
        image: restfulci/job-master-api-server:c72dcd06192aeaf7ec45546cbd3da4caf5cc61eb
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        resources:
          requests:
            cpu: 50m
