apiVersion: apps/v1
kind: Deployment
metadata:
  name: restfulci-job-postgres
  namespace: job-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          # Currently we simply baked the Postgres schema into the image.
          #
          # Alternatively,
          # We should either add a ConfigMap which contains the schema,
          # and potentially generate it from file through Kustomize
          # configMapGenerator:
          # https://kubectl.docs.kubernetes.io/pages/app_management/secrets_and_configmaps.html
          #
          # Or we can bake `setup.sql` into `/docker-entrypoint-initdb.d` into
          # an image (need a docker hub storage then). It is kind of less
          # important, because we probably need to handle liquibase (as a Kubernetes
          # job) anyway.
          image: restfulci/job-postgres:8d55b5032a2ab9cfe01bf02bebe0f122b045b0ed
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: restfulci-job
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          resources:
            requests:
              cpu: 50m
