apiVersion: apps/v1
kind: Deployment
metadata:
  name: restfulci-job-rabbitmq
  namespace: job-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8.2-management
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          requests:
            cpu: 300m

# May consider refer to:
# https://zupzup.org/k8s-rabbitmq-cluster/
