version: "3"
services:

  pipeline-postgres:
    image: postgres:14.2
    ports:
      - "5433:5432"
    volumes:
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - POSTGRES_DB=restfulci-pipeline
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  job-microservice-mock:
    build:
      context: ./job-microservice-mock
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    tty: true
    restart: always
