version: "3"
services:

  pipeline-postgres:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_DB=restfulci-pipeline
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  job-microservice-mock:
    build:
      context: ./job-microservice-mock
      dockerfile: ./Dockerfile
    tty: true
    restart: always

  pipeline-api-cron-server:
    # image: restfulci/pipeline-api-cron-server:2a346993246acc2d8763b82df878109b253e0e1b-dirty
    build:
      context: ./api-cron
      dockerfile: ./Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8882:8080"
    depends_on:
      - pipeline-postgres
      - job-microservice-mock
    tty: true
    restart: always
