version: "3"
services:

  pipeline-postgres:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_DB=restfulci-pipeline
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  job-microservice-mock:
    build:
      context: ./job-microservice-mock
      dockerfile: ./Dockerfile
    tty: true
    restart: always

  pipeline-api-cron-server:
    # image: restfulci/pipeline-api-cron-server:2a346993246acc2d8763b82df878109b253e0e1b-dirty
    build:
      context: ./api-cron
      dockerfile: ./Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH_SERVER_URI=http://localhost:8880
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8882:8080"
    depends_on:
      - pipeline-postgres
      - job-microservice-mock
      - keycloak
    tty: true
    restart: always

  keycloak:
    image: restfulci/auth-server-local:8da072f0160c76d9698c4bd7374644022925d8ab
    ports:
      # TODO:
      # Use 8443 instand for SSL.
      - "8880:8080"
    environment:
      KEYCLOAK_USER: restfulci
      KEYCLOAK_PASSWORD: secretpassword
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - keycloak-postgres

  keycloak-postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
