version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:11.0.2-jdk

    working_directory: /tmp/java

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

  java-with-sidecar-executor:
    docker:
      - image: cimg/openjdk:15.0.1
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/restfulci

      - image: postgres:14.2
        environment:
          POSTGRES_DB: restfulci
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      - image: rabbitmq:3.8.9

    working_directory: /tmp/java

    environment:
      CI: CircleCI
      SPRING_PROFILES_ACTIVE: circleci
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

  python-executor:
    docker:
      - image: circleci/python:3.7.3

    working_directory: ~/python

orbs:
  inline-postgres-job:
    commands:
      initialize:
        steps:
          - run: sudo apt-get update || sudo apt-get update && sudo apt install postgresql-client
          - run: psql -U postgres -h localhost -d restfulci -p 5432 -w -f job-microservice/database/setup.sql

  inline-postgres-pipeline:
    commands:
      initialize:
        steps:
          - run: sudo apt-get update || sudo apt-get update && sudo apt install postgresql-client
          - run: psql -U postgres -h localhost -d restfulci -p 5432 -w -f pipeline-microservice/database/setup.sql

  inline-minio:
    commands:
      installation:
        steps:
          - run:
              name: run minIO server
              command: |
                wget https://dl.min.io/server/minio/release/linux-amd64/minio -qO minio
                chmod +x minio
                sudo mv minio /usr/local/bin/minio
                minio server /tmp/data
              background: true
              environment:
                MINIO_UPDATE: 'off'
                MINIO_ACCESS_KEY: restfulci
                MINIO_SECRET_KEY: secretpassword

  hugo: circleci/hugo@1.0.0

jobs:
  java-job-unittest:
    executor: java-with-sidecar-executor
    steps:
      - checkout
      - inline-postgres-job/initialize
      - inline-minio/installation

      # This is to support running docker-java related unit tests.
      - setup_remote_docker:
          docker_layer_caching: false

      - run: cd job-microservice && mvn test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/
            find . -type f -regex "./job-microservice/.*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/ \;
          when: always
      - store_test_results:
          path: ~/test-results/

  java-job-integration-test:
    executor: java-with-sidecar-executor
    steps:
      - checkout
      - inline-postgres-job/initialize
      - inline-minio/installation

      - run: cd job-microservice && mvn verify -Dskip.unittest=true

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/
            find . -type f -regex "./job-microservice/.*/target/failsafe-reports/.*xml" -exec cp {} ~/test-results/ \;
          when: always
      - store_test_results:
          path: ~/test-results/

  java-job-build-docker-push:
    executor: java-executor
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false

      - run: cd job-microservice && mvn package -Dskip.unittest=true -Dskip.it=true

      - run:
          name: Build and push job-master-api-server docker image
          command: |
            cd job-microservice/master-api && docker build -t restfulci/job-master-api-server:$CIRCLE_SHA1 .
            echo $DOCKER_PWD | docker login -u $DOCKER_ID --password-stdin
            docker push restfulci/job-master-api-server:$CIRCLE_SHA1

      - run:
          name: Build and push job-slave-executor docker image
          command: |
            cd job-microservice/slave-agent && docker build -t restfulci/job-slave-executor:$CIRCLE_SHA1 .
            echo $DOCKER_PWD | docker login -u $DOCKER_ID --password-stdin
            docker push restfulci/job-slave-executor:$CIRCLE_SHA1

      - run:
          name: Build and push job-postgres docker image
          command: |
            cd job-microservice/database && docker build -t restfulci/job-postgres:$CIRCLE_SHA1 .
            echo $DOCKER_PWD | docker login -u $DOCKER_ID --password-stdin
            docker push restfulci/job-postgres:$CIRCLE_SHA1

  java-pipeline-unittest:
    executor: java-with-sidecar-executor
    steps:
      - checkout
      - inline-postgres-pipeline/initialize

      - run: cd pipeline-microservice/api-cron && mvn test

      - store_test_results:
          path: pipeline-microservice/api-cron/target/surefire-reports/

  java-pipeline-integration-test:
    executor: java-with-sidecar-executor
    steps:
      - checkout
      - inline-postgres-pipeline/initialize

      - run: cd pipeline-microservice/api-cron && mvn verify -Dskip.unittest=true

      - store_test_results:
          path: pipeline-microservice/api-cron/target/failsafe-reports/

  java-pipeline-build-docker-push:
    executor: java-executor
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false

      - run: cd pipeline-microservice/api-cron && mvn package -Dskip.unittest=true -Dskip.it=true

      - run:
          name: Build and push pipeline-api-cron-server docker image
          command: |
            cd pipeline-microservice/api-cron && docker build -t restfulci/pipeline-api-cron-server:$CIRCLE_SHA1 .
            echo $DOCKER_PWD | docker login -u $DOCKER_ID --password-stdin
            docker push restfulci/pipeline-api-cron-server:$CIRCLE_SHA1

      - run:
          name: Build and push pipeline-postgres docker image
          command: |
            cd pipeline-microservice/database && docker build -t restfulci/pipeline-postgres:$CIRCLE_SHA1 .
            echo $DOCKER_PWD | docker login -u $DOCKER_ID --password-stdin
            docker push restfulci/pipeline-postgres:$CIRCLE_SHA1

  python-linter:
    executor: python-executor
    steps:
      - checkout

      - run: sudo pip3 install pipenv

      - run: cd e2e-api && pipenv install flake8
      - run: cd e2e-api && pipenv run flake8 --statistics

      - run: cd pipeline-microservice/job-microservice-mock && pipenv install flake8
      - run: cd pipeline-microservice/job-microservice-mock && pipenv run flake8 --statistics

  js-vue-linter:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/js
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "job-frontend/yarn.lock" }}
      - run:
          name: Install Dependencies
          command: cd job-frontend && yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "job-frontend/yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: # run tests
          name: linter
          command: cd job-frontend && node_modules/.bin/eslint --ext .js,.vue .

  job-frontend-docker-push:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/js
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false

      - run: cd job-frontend

      - run:
          name: Build and push job-frontend docker image
          command: |
            cd job-frontend && docker build -t restfulci/job-frontend:$CIRCLE_SHA1 .
            echo $DOCKER_PWD | docker login -u $DOCKER_ID --password-stdin
            docker push restfulci/job-frontend:$CIRCLE_SHA1

  keycloak-build-docker-push:
    executor: python-executor
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false

      - run: sudo pip3 install jsonpatch
      - run: cd auth-microservice && sh patch.sh

      # Alternatively we can define multiple realms in a single image.
      #
      # None of the below suggestion works:
      # https://www.codetd.com/en/article/7462535
      # https://stackoverflow.com/a/61236608/2467072
      #
      # And probably it is better/safer the container only include
      # one realm.
      - run:
          name: Build and push auth-microservice docker images
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_ID --password-stdin
            cd auth-microservice

            docker build --build-arg AUTH_ENV=local -t restfulci/auth-server-local:$CIRCLE_SHA1 .
            docker push restfulci/auth-server-local:$CIRCLE_SHA1

            docker build --build-arg AUTH_ENV=docker -t restfulci/auth-server-docker:$CIRCLE_SHA1 .
            docker push restfulci/auth-server-docker:$CIRCLE_SHA1

            docker build --build-arg AUTH_ENV=kubernetes -t restfulci/auth-server-kubernetes:$CIRCLE_SHA1 .
            docker push restfulci/auth-server-kubernetes:$CIRCLE_SHA1

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - java-job-unittest
      - java-job-integration-test
      - java-job-build-docker-push:
          requires:
            - java-job-unittest
            - java-job-integration-test
          filters:
            branches:
              only: master

      - java-pipeline-unittest
      - java-pipeline-integration-test
      - java-pipeline-build-docker-push:
          requires:
            - java-pipeline-unittest
            - java-pipeline-integration-test
          filters:
            branches:
              only: master

      - python-linter
      - js-vue-linter

      - job-frontend-docker-push:
          requires:
            - js-vue-linter
          filters:
            branches:
              only: master

      - keycloak-build-docker-push:
          filters:
            branches:
              only: master

      - hugo/build:
          html-proofer: true
          source: documentation/
          version: '0.74.3'
