apiVersion: apps/v1

kind: Deployment
metadata:
  name: restfulci-pipeline-api-cron-server
  namespace: pipeline-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api-cron-server
  template:
    metadata:
      labels:
        app: api-cron-server
    spec:
      containers:
      - name: api-cron-server
        image: restfulci/pipeline-api-cron-server:32391688cb89676ffdc88dd43ddf35add6f391ea
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        resources:
          requests:
            cpu: 50m
