apiVersion: v1

kind: Service
metadata:
  name: restfulci-pipeline-api-cron-server
  namespace: pipeline
  labels:
    app: api-cron-server
spec:
  type: LoadBalancer
  selector:
    app: api-cron-server
  ports:
  - port: 80
    targetPort: 8080
