apiVersion: apps/v1

kind: Deployment
metadata:
  name: restfulci-pipeline-api-cron-server
  namespace: pipeline-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api-cron-server
  template:
    metadata:
      labels:
        app: api-cron-server
    spec:
      containers:
      - name: api-cron-server
        image: restfulci/pipeline-api-cron-server:8da072f0160c76d9698c4bd7374644022925d8ab
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        resources:
          requests:
            cpu: 50m
