apiVersion: v1
kind: Service
metadata:
  name: restfulci-pipeline-postgres
  namespace: pipeline
  labels:
    app: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - port: 5432
