apiVersion: v1

kind: Service
metadata:
  name: restfulci-job-frontend
  namespace: job-frontend
  labels:
    app: job-frontend
spec:
  type: LoadBalancer
  selector:
    app: job-frontend
  ports:
  - port: 80
    targetPort: 5000
