version: "3"
services:

  job-postgres:
    image: restfulci/job-postgres:85d65d5882575a554aa605158d16beacae4ba499
    environment:
      # TODO: Change name from `restfulci` to `restfulci-job`
      - POSTGRES_DB=restfulci
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  job-rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - "15673:15672"

  job-minio:
    image: minio/minio:RELEASE.2020-12-26T01-35-54Z
    environment:
      - MINIO_ACCESS_KEY=restfulci
      - MINIO_SECRET_KEY=secretpassword
    command: server /data

  job-master-api-server:
    image: restfulci/job-master-api-server:85d65d5882575a554aa605158d16beacae4ba499
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH_SERVER=http://localhost:8880
    ports:
      - "8881:8080"
    depends_on:
      - job-postgres
      - job-rabbitmq
      - job-minio
      - keycloak
    tty: true
    restart: always

  job-slave-executor:
    image: restfulci/job-slave-executor:85d65d5882575a554aa605158d16beacae4ba499
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $SSH_AUTH_SOCK:${SSH_AUTH_SOCK}
    environment:
      - SSH_AUTH_SOCK
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - job-postgres
      - job-rabbitmq
      - job-minio
    tty: true
    restart: always

  keycloak:
    image: restfulci/auth-server-docker:85d65d5882575a554aa605158d16beacae4ba499
    ports:
      # TODO:
      # Use 8443 instand for SSL.
      - "8880:8080"
    environment:
      KEYCLOAK_USER: restfulci
      KEYCLOAK_PASSWORD: secretpassword
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - keycloak-postgres

  keycloak-postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  job-frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5111:5000"
    environment:
      # This needs to be the API path to be seen from the browser, rather
      # than the API path seen from the docker container (more specifically,
      # in docker-compose http://master-api-server:8080/ will not work).
      # It is because this path is in `_nuxt/app.***.js` executed in inside of
      # the browser.
      API_SERVER: http://localhost:8881
      AUTH_SERVER: http://localhost:8880
    depends_on:
      - job-master-api-server
    tty: true
    restart: always
