version: "3"
services:

  postgres:
    image: restfulci/job-postgres:600166251d2c762aecec38acc91dcb976e3260b0
    environment:
      # TODO: Change name from `restfulci` to `restfulci-job`
      - POSTGRES_DB=restfulci
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  rabbitmq:
    image: rabbitmq:3.8.2-management
    ports:
      - "15673:15672"

  minio:
    image: minio/minio:RELEASE.2020-04-02T21-34-49Z
    environment:
      - MINIO_ACCESS_KEY=restfulci
      - MINIO_SECRET_KEY=secretpassword
    command: server /data

  master-api-server:
    image: restfulci/job-master-api-server:600166251d2c762aecec38acc91dcb976e3260b0
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8881:8080"
    depends_on:
      - postgres
      - rabbitmq
      - minio
    tty: true
    restart: always

  slave-executor:
    image: restfulci/job-slave-executor:600166251d2c762aecec38acc91dcb976e3260b0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $SSH_AUTH_SOCK:${SSH_AUTH_SOCK}
    environment:
      - SSH_AUTH_SOCK
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - rabbitmq
      - minio
    tty: true
    restart: always
