apiVersion: apps/v1
kind: Deployment
metadata:
  name: restfulci-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: restfulci-postgres
          resources:
            requests:
              cpu: 50m
      #     volumeMounts:
      #       - mountPath: /var/lib/postgresql/data
      #         name: postgredb
      # volumes:
      #   - name: postgredb
      #     persistentVolumeClaim:
      #       claimName: postgres-pv-claim
