apiVersion: v1
kind: Service
metadata:
  name: restfulci-rabbitmq
  labels:
    app: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: http
    protocol: TCP
    port: 15672
    targetPort: 15672
