baseURL = "/"
languageCode = "en-us"
title = "RestfulCI"
description = "Kube is a professional  and a responsive Hugo theme for developers and designers that offers a documentation section mixed with a landing page and a blog"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "RestfulCI" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "Install"
    weight = -100
    url = "/docs/quick-start/"
[[menu.main]]
    name = "Documentation"
    weight = -99
    url = "/docs/"
[[menu.main]]
    name = "Use cases"
    weight = -99
    url = "/use-cases/"
[[menu.main]]
    name = "Blog"
    weight = -98
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -97
    url = "/faq/"
